### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jonathom** [jonathom/detect_deforestation#1]
- [x] create 3 monthly data @PondiB 
- [x] Gapfill
    - [x] monthly @jonathom
    - [x] 3 monthly @PondiB 
    - [x] exchange data @PondiB @jonathom
- [x] doing bfastmonitor on whole tile @jonathom @PondiB wednesday or thursday
- [x] result computation: classified raster @jonathom @PondiB wednesday or thursday
- [x] validation method 
    - [x] find methods. see [accuracy metrics](http://gis.humboldt.edu/OLM/Courses/GSP_216_Online/lesson6-2/metrics.html) @jonathom 
    - [x] accuracy metrics: producers & users accuracy @jonathom 
    - [x] kappa @jonathom 
- [x] paper
    - [x] introduction @PondiB 
    - [x] methods @PondiB 
    - [x] results @PondiB  @jonathom 
    - [x] discussion  @jonathom 
    - [x] conclusion @PondiB  @jonathom

**Comment by jonathom** [comment]
- [ ] convert Gapfill back to stars @jonathom

**Comment by jonathom** [comment]
new extent: `v = cube_view(srs="EPSG:3857", extent=list(left = -7366000, right = -7314864, top = -995476.1, bottom = -1046612, t0 ="2013-01-01", t1 = "2019-12-31"), dx=60, dy=60, dt = "P1M", resampling = "average", aggregation = "median")`

* 2013 - 2019
* `left = -7366000, right = -7314864, top = -995476.1, bottom = -1046612`

**Comment by PondiB** [comment]
Great, new extents factored in.

**Comment by jonathom** [comment]
new, smaller extent is `left = -7338335, right = -7329987, top = -1018790, bottom = -1027138`, its 140 pixels square and should be ok for Gapfill in 6-8 hours, less with monthly data of course.

**Comment by PondiB** [comment]
Factored in.

**Comment by jonathom** [comment]
haha thanks @PondiB. Only thing missing now is an evaluation @edzer ;)

**Comment by PondiB** [comment]
@jonathom , sure hahaha. Taking a lifetime
